[package]
name = "cobblepot_core"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "core.rs"

[dependencies]
log.workspace = true
toml.workspace = true
serde.workspace = true
