[package]
name = "cobblepot_data_store"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "data_store.rs"

[dependencies]
diesel.workspace = true
log.workspace = true
serde.workspace = true
chrono.workspace = true
